"""
Database Models.

This file defines the SQLAlchemy ORM models for the application's database schema.
Models:
- User: Stores user account information and handles password hashing.
- EmissionFactor: Stores the GHG Protocol emission factors.
- UserInput: Stores individual activity data inputs from users.
- Report: Stores aggregated emission reports generated by users.
"""

from . import db, bcrypt
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

class User(db.Model):
    """
    User Model
    Stores user credentials and profile information.
    """
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    company_name = db.Column(db.String(120), nullable=True)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    inputs = relationship('UserInput', back_populates='user', lazy='dynamic')
    reports = relationship('Report', back_populates='user', lazy='dynamic')

    def __init__(self, username, email, password, company_name=None):
        """
        Initialize the User model and hash the password.
        """
        self.username = username
        self.email = email
        self.password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
        self.company_name = company_name

    def check_password(self, password):
        """
        Check if the provided password matches the stored hash.
        """
        return bcrypt.check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'


class EmissionFactor(db.Model):
    """
    Emission Factor Model
    Stores reference data for GHG calculations.
    """
    __tablename__ = 'emission_factors'
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    category = db.Column(db.String(100), nullable=False) # e.g., "Fuel", "Electricity", "Travel"
    scope = db.Column(db.Integer, nullable=False)      # 1, 2, or 3
    factor_value = db.Column(db.Float, nullable=False) # The emission factor
    unit = db.Column(db.String(50), nullable=False)    # The unit of the factor, e.g., "liter", "kWh", "km"
    co2e_unit = db.Column(db.String(50), nullable=False, default='kg CO2e') # Unit of the result
    source = db.Column(db.String(255), nullable=True)  # e.g., "EPA eGRID 2023", "DEFRA 2023"
    
    # Relationships
    inputs = relationship('UserInput', back_populates='factor')

    def to_dict(self):
        """Return a dictionary representation of the model."""
        return {
            'id': self.id,
            'name': self.name,
            'category': self.category,
            'scope': self.scope,
            'factor_value': self.factor_value,
            'unit': self.unit,
            'co2e_unit': self.co2e_unit,
            'source': self.source
        }

    def __repr__(self):
        return f'<EmissionFactor {self.name}>'


class UserInput(db.Model):
    """
    User Input Model
    Stores a single activity data point from a user.
    """
    __tablename__ = 'user_inputs'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    factor_id = db.Column(db.Integer, db.ForeignKey('emission_factors.id'), nullable=False)
    
    activity_value = db.Column(db.Float, nullable=False) # e.g., 1000
    activity_unit = db.Column(db.String(50), nullable=False) # e.g., "liter"
    
    date_period_start = db.Column(db.Date, nullable=False)
    date_period_end = db.Column(db.Date, nullable=True)
    
    # The result of the calculation
    calculated_emissions_kg = db.Column(db.Float, nullable=False)
    
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    user = relationship('User', back_populates='inputs')
    factor = relationship('EmissionFactor', back_populates='inputs')

    def to_dict(self):
        """Return a dictionary representation of the model."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'factor_id': self.factor_id,
            'factor_name': self.factor.name,
            'scope': self.factor.scope,
            'activity_value': self.activity_value,
            'activity_unit': self.activity_unit,
            'date_period_start': self.date_period_start.isoformat(),
            'calculated_emissions_kg': self.calculated_emissions_kg,
            'created_at': self.created_at.isoformat()
        }

    def __repr__(self):
        return f'<UserInput {self.id} for User {self.user_id}>'


class Report(db.Model):
    """
    Report Model
    Stores aggregated snapshots of emissions for a user over a time period.
    """
    __tablename__ = 'reports'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    
    report_name = db.Column(db.String(255), nullable=False)
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)
    
    total_scope1_kg = db.Column(db.Float, nullable=False, default=0.0)
    total_scope2_kg = db.Column(db.Float, nullable=False, default=0.0)
    total_scope3_kg = db.Column(db.Float, nullable=False, default=0.0)
    total_all_scopes_kg = db.Column(db.Float, nullable=False, default=0.0)
    
    generated_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    user = relationship('User', back_populates='reports')

    def to_dict(self):
        """Return a dictionary representation of the model."""
        return {
            'id': self.id,
            'report_name': self.report_name,
            'start_date': self.start_date.isoformat(),
            'end_date': self.end_date.isoformat(),
            'total_scope1_kg': self.total_scope1_kg,
            'total_scope2_kg': self.total_scope2_kg,
            'total_scope3_kg': self.total_scope3_kg,
            'total_all_scopes_kg': self.total_all_scopes_kg,
            'generated_at': self.generated_at.isoformat()
        }
        
    def __repr__(self):
        return f'<Report {self.report_name} for User {self.user_id}>'